<!--[if lt IE 9]>
<script src="https://static.bbc.co.uk/indepthtoolkit/6.0.0/js/vendor/polyfil.js"></script>
<![endif]-->
<style>
.ns-panel-edgware__clickable {
  display: none;
}
.ns-panel-edgware__hotspots {
  display: none;
}
.ns-panel-edgware__section-close{
  display: none;
}
.ns-panel-edgware--interactive .ns-panel-edgware__clickable {
  display: block;
}
.ns-panel-edgware--interactive .ns-panel-edgware__hotspots {
  display: block;
}
.ns-panel-edgware--interactive .ns-panel-edgware__video__cta{
  display: none;
}
body ul .ns-panel-edgware__section {
  background: none;
  list-style: none;
  margin: 0 0 1em;
  padding-left: 0;
}
</style>
<script>
document.body.className += " dyn_full";
</script>

<div class="idt__news ns-panel-edgware ns-wide-include" id="ns_clickableguide-35533287">

    <div class="ns-panel-edgware__clickable">INTERACTIVE</div>

    <div class="ns-panel-edgware__hotspots ns-panel-edgware__hotspots--thumbnail" style="height: 550px;">

                <noscript>
            <img src="http://c.files.bbci.co.uk/CD55/production/_83956525_7_7_edgware_rd_976.png" width="976" height="550" alt="Locations of those killed and those who survived the Edgware Road bombing" class="no-replace"  />
        </noscript>

        <div class="idt-delayed-image-load ns-panel-edgware__context-image" data-src="http://c.files.bbci.co.uk/CD55/production/_83956525_7_7_edgware_rd_976.png" data-alt="Locations of those killed and those who survived the Edgware Road bombing" ></div>

            
        
        <a href="#ns-panel-edgware__section-2" class="ns-panel-edgware__hotspot ns-panel-edgware__hotspot--2 ns-panel-edgware__hotspot--no-hover-border" style="position: absolute; left: 0px; top: 112px; width: 100px; height: 125px; ">
                            <div class="ns-panel-edgware__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-edgware__caption-overlay ">
                    <p>Catherine Al-Wafai</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-edgware__section-3" class="ns-panel-edgware__hotspot ns-panel-edgware__hotspot--3 ns-panel-edgware__hotspot--no-hover-border" style="position: absolute; left: 363px; top: 112px; width: 102px; height: 125px; ">
                            <div class="ns-panel-edgware__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-edgware__caption-overlay ">
                    <p>John Tulloch</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-edgware__section-4" class="ns-panel-edgware__hotspot ns-panel-edgware__hotspot--4 ns-panel-edgware__hotspot--no-hover-border" style="position: absolute; left: 122px; top: 111px; width: 103px; height: 124px; ">
                            <div class="ns-panel-edgware__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-edgware__caption-overlay ">
                    <p>Daniel Biddle</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-edgware__section-5" class="ns-panel-edgware__hotspot ns-panel-edgware__hotspot--5 ns-panel-edgware__hotspot--no-hover-border" style="position: absolute; left: 243px; top: 112px; width: 101px; height: 123px; ">
                            <div class="ns-panel-edgware__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-edgware__caption-overlay ">
                    <p>David Gardner</p>
                </span>
                    </a>

        
    
    </div>

    <ul class="ns-panel-edgware__sections">
                <li class="ns-panel-edgware__section ns-panel-edgware__section--int" id="ns-panel-edgware__section-2">

        <h2 class="ns-panel-edgware__section-header">Catherine Al-Wafai</h2>
        
        <a class="ns-panel-edgware__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-edgware__section-sub-header"></h3>
        
        <div class="ns-panel-edgware__section-text">
            <p><a href='http://webarchive.nationalarchives.gov.uk/20120216072438/http://7julyinquests.independent.gov.uk/hearing_transcripts/10112010am.htm' TARGET=''>Ms Al-Wafai,</a> who suffered small injuries to her arm and thigh, was on her way to a job interview when the blast happened, severely injuring a woman to her left. Covered in blood, Ms Al-Wafai walked away unaided from the scene. Emerging from the Tube, she found staff from a nearby Marks and Spencer store helping survivors. She only realised she had lost a shoe when she arrived home. 'I collapsed in the hallway and just curled up,' she said.</p>        </div>
    </li>
    <li class="ns-panel-edgware__section ns-panel-edgware__section--int" id="ns-panel-edgware__section-3">

        <h2 class="ns-panel-edgware__section-header">John Tulloch</h2>
        
        <a class="ns-panel-edgware__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-edgware__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-edgware__section-img no-replace" src="http://c.files.bbci.co.uk/0F37/production/_83959830_john_tulloch_creditgetty_62.jpg" alt="John Tulloch" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-edgware__section-img" data-src="http://c.files.bbci.co.uk/0F37/production/_83959830_john_tulloch_creditgetty_62.jpg" data-alt="John Tulloch"></div>
         
        <div class="ns-panel-edgware__section-text">
            <p>Professor John Tulloch was sitting on the opposite side of the carriage from Mohammed Sidique Khan. Mr Tulloch had returned from Australia a few days before the bombing and had yet to go home to Cardiff, so was carrying three bags with him. A hard suitcase by his feet saved him from serious injury. Prof Tulloch's left ear drum was perforated and shrapnel from the blast is still embedded in his head.</p>        </div>
    </li>
    <li class="ns-panel-edgware__section ns-panel-edgware__section--int" id="ns-panel-edgware__section-4">

        <h2 class="ns-panel-edgware__section-header">Daniel Biddle</h2>
        
        <a class="ns-panel-edgware__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-edgware__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-edgware__section-img no-replace" src="http://c.files.bbci.co.uk/12813/production/_83959757_daniel_biddle_credit_624.jpg" alt="Daniel Biddle" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-edgware__section-img" data-src="http://c.files.bbci.co.uk/12813/production/_83959757_daniel_biddle_credit_624.jpg" data-alt="Daniel Biddle"></div>
         
        <div class="ns-panel-edgware__section-text">
            <p>Daniel Biddle, running late for work, was standing close to plot ringleader Mohammad Sidique Khan when the bomb exploded. He described seeing Khan's arm move quickly and then a 'big, white flash'. The construction manager was blown from the carriage and lost both legs, his left eye and his spleen. He was helped by a fellow passenger who made tourniquets from his belt and shirt. A 20p piece remains lodged in Mr Biddle's thigh bone, and other shrapnel, including his door keys, was removed by surgeons.</p>        </div>
    </li>
    <li class="ns-panel-edgware__section ns-panel-edgware__section--int" id="ns-panel-edgware__section-5">

        <h2 class="ns-panel-edgware__section-header">David Gardner</h2>
        
        <a class="ns-panel-edgware__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-edgware__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-edgware__section-img no-replace" src="http://c.files.bbci.co.uk/B6CB/production/_83959764_david_gardner_credit_624.jpg" alt="David Gardner" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-edgware__section-img" data-src="http://c.files.bbci.co.uk/B6CB/production/_83959764_david_gardner_credit_624.jpg" data-alt="David Gardner"></div>
         
        <div class="ns-panel-edgware__section-text">
            <p>David Gardner, a management accountant at the Evening Standard, lost his left leg and spleen in the attacks. He was blown off his seat and onto the carriage floor, where he drifted in and out of consciousness while fellow passenger Jason Rennie, an ex-Army officer, made a tourniquet for his badly-damaged left leg. Mr Gardner had been due to direct a performance of Shakespeare's Julius Caesar and was reading the script when the bomb exploded.</p>        </div>
    </li>
    </ul>
</div>

<script>
(function () {
    require(['special/2015/newsspec_11531/edgware/ns_clickableguide_all-edgware.js'], function () {
        require(['js/clickableguide/main-2', 'cssp!http://news.bbcimg.co.uk/news/special/2015/newsspec_11531/edgware/ns_panels_core_domestic-edgware_v9.css?csspHack'], function (ClickableGuide) {
            var myClickableGuide = new ClickableGuide('#ns_clickableguide-35533287', {
                next:          "Next",
                pagingDivider: "of",
                prev:          "Previous",
                nextImage:     "Next image",
                prevImage:     "Previous image"
            }, {
                nextPrevButtons:      false,
                responsive:           (window.bbcNewsResponsive || false),
                interactiveMinWidth:  976 + 47,
                interactiveMinHeight: 550,
                mask:                 '',
                panelsPosition:       'centre_of_interactive',
                zoomable_images:      false            });
        });
    });
}());
</script>

<div id="csspHack"></div>