<!--newsspec_11531 tavistock -->
<div id="newsspec-11531-responsive-image-include-4" class="ns-responsive-image-placeholder"></div>
<script type="text/javascript">
require(['http://news.bbcimg.co.uk/news/special/2015/newsspec_11297/art_direction_rwdimg/v5/js/artdirectionrwdimg.js'], function (artDirectionRwdImg){
    artDirectionRwdImg(
        {
            "namespaceId": "newsspec-11531-responsive-image-include-4",
            "images": {
                    "305" : "2015/newsspec_11531/tavistock/img/7_7_tavistock_305.png",
                    "448" : "2015/newsspec_11531/tavistock/img/7_7_tavistock_448.png",
                    "624" : "2015/newsspec_11531/tavistock/img/7_7_tavistock_624.png"
                },
            "alt": "Location of bomber and passengers in the Tavistock Square blast",
            "caption": ""
        }
    );
});
</script>