<!--[if lt IE 9]>
<script src="https://static.bbc.co.uk/indepthtoolkit/6.0.0/js/vendor/polyfil.js"></script>
<![endif]-->
<style>
.ns-panel-tavistock__clickable {
  display: none;
}
.ns-panel-tavistock__hotspots {
  display: none;
}
.ns-panel-tavistock__section-close{
  display: none;
}
.ns-panel-tavistock--interactive .ns-panel-tavistock__clickable {
  display: block;
}
.ns-panel-tavistock--interactive .ns-panel-tavistock__hotspots {
  display: block;
}
.ns-panel-tavistock--interactive .ns-panel-tavistock__video__cta{
  display: none;
}
body ul .ns-panel-tavistock__section {
  background: none;
  list-style: none;
  margin: 0 0 1em;
  padding-left: 0;
}
</style>
<script>
document.body.className += " dyn_full";
</script>

<div class="idt__news ns-panel-tavistock ns-wide-include" id="ns_clickableguide-29176876">

    <div class="ns-panel-tavistock__clickable">INTERACTIVE</div>

    <div class="ns-panel-tavistock__hotspots ns-panel-tavistock__hotspots--thumbnail" style="height: 720px;">

                <noscript>
            <img src="http://c.files.bbci.co.uk/1D27/production/_84036470_7_7_tavistock_square_976.png" width="976" height="720" alt="Graphic of the Tavistock Square bombing" class="no-replace"  />
        </noscript>

        <div class="idt-delayed-image-load ns-panel-tavistock__context-image" data-src="http://c.files.bbci.co.uk/1D27/production/_84036470_7_7_tavistock_square_976.png" data-alt="Graphic of the Tavistock Square bombing" ></div>

            
        
        <a href="#ns-panel-tavistock__section-2" class="ns-panel-tavistock__hotspot ns-panel-tavistock__hotspot--2 ns-panel-tavistock__hotspot--no-hover-border" style="position: absolute; left: 510px; top: 280px; width: 101px; height: 136px; ">
                            <div class="ns-panel-tavistock__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-tavistock__caption-overlay ">
                    <p>George Psaradakis</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-tavistock__section-3" class="ns-panel-tavistock__hotspot ns-panel-tavistock__hotspot--3 ns-panel-tavistock__hotspot--no-hover-border" style="position: absolute; left: 868px; top: 278px; width: 103px; height: 138px; ">
                            <div class="ns-panel-tavistock__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-tavistock__caption-overlay ">
                    <p>Louise Barry</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-tavistock__section-4" class="ns-panel-tavistock__hotspot ns-panel-tavistock__hotspot--4 ns-panel-tavistock__hotspot--no-hover-border" style="position: absolute; left: 751px; top: 281px; width: 101px; height: 159px; ">
                            <div class="ns-panel-tavistock__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-tavistock__caption-overlay ">
                    <p>Camille Scott-Bradshaw</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-tavistock__section-5" class="ns-panel-tavistock__hotspot ns-panel-tavistock__hotspot--5 ns-panel-tavistock__hotspot--no-hover-border" style="position: absolute; left: 629px; top: 279px; width: 102px; height: 137px; ">
                            <div class="ns-panel-tavistock__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-tavistock__caption-overlay ">
                    <p>Lisa French</p>
                </span>
                    </a>

        
    
    </div>

    <ul class="ns-panel-tavistock__sections">
                <li class="ns-panel-tavistock__section ns-panel-tavistock__section--int" id="ns-panel-tavistock__section-2">

        <h2 class="ns-panel-tavistock__section-header">George Psaradakis</h2>
        
        <a class="ns-panel-tavistock__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-tavistock__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-tavistock__section-img no-replace" src="http://c.files.bbci.co.uk/44BB/production/_83959571_george_psaradakis_gettycred.jpg" alt="George Psaradakis" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-tavistock__section-img" data-src="http://c.files.bbci.co.uk/44BB/production/_83959571_george_psaradakis_gettycred.jpg" data-alt="George Psaradakis"></div>
         
        <div class="ns-panel-tavistock__section-text">
            <p>Greek-born bus driver Mr Psaradakis had been forced to depart from his normal number 30 route on the day of the blast because of police blocking the road. He told the inquest that up to 50 people had disembarked from the bus because of the route change moments before the explosion tore through the vehicle. Mr Psaradakis described trying to help the injured. 'Seeing my passengers in such a state really shocked me, I was overwhelmed,' he said.</p>        </div>
    </li>
    <li class="ns-panel-tavistock__section ns-panel-tavistock__section--int" id="ns-panel-tavistock__section-3">

        <h2 class="ns-panel-tavistock__section-header">Louise Barry</h2>
        
        <a class="ns-panel-tavistock__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-tavistock__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-tavistock__section-img no-replace" src="http://c.files.bbci.co.uk/123C7/production/_83959647_louise_barry_gettycredit_62.jpg" alt="Louise Barry" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-tavistock__section-img" data-src="http://c.files.bbci.co.uk/123C7/production/_83959647_louise_barry_gettycredit_62.jpg" data-alt="Louise Barry"></div>
         
        <div class="ns-panel-tavistock__section-text">
            <p>Ms Barry, who suffered injuries to her arm, leg and head, had been evacuated from the Underground at Edgware Road after one of the three earlier blasts, only to be caught in the explosion at Tavistock Square. The Australian at first thought she was having some kind of seizure, but then felt boiling water from the bus's radiator dripping on her arm. Thinking it was petrol, she described crawling through bodies to escape.</p>        </div>
    </li>
    <li class="ns-panel-tavistock__section ns-panel-tavistock__section--int" id="ns-panel-tavistock__section-4">

        <h2 class="ns-panel-tavistock__section-header">Camille Scott-Bradshaw</h2>
        
        <a class="ns-panel-tavistock__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-tavistock__section-sub-header"></h3>
        
        <div class="ns-panel-tavistock__section-text">
            <p>Ms Scott-Bradshaw, on a day trip to London from Lancashire for work, lost friend and colleague Marie Hartley in the explosion. The designer, who suffered severe leg injuries and damage to her hearing, tried to find her friend in the courtyard of a nearby building. 'I just remember looking over and I think, in the corner, there were bodies... and I could see Marie... I knew it was Marie because I could see her hair, her bracelet and her arms.'</p>        </div>
    </li>
    <li class="ns-panel-tavistock__section ns-panel-tavistock__section--int" id="ns-panel-tavistock__section-5">

        <h2 class="ns-panel-tavistock__section-header">Lisa French</h2>
        
        <a class="ns-panel-tavistock__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-tavistock__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-tavistock__section-img no-replace" src="http://c.files.bbci.co.uk/B9EB/production/_83959574_lisa_french_bbccredit_624.jpg" alt="Lisa French" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-tavistock__section-img" data-src="http://c.files.bbci.co.uk/B9EB/production/_83959574_lisa_french_bbccredit_624.jpg" data-alt="Lisa French"></div>
         
        <div class="ns-panel-tavistock__section-text">
            <p>Ms French decided not to sit next to bomber Hasib Hussain because there was not enough room for her laptop as well as his rucksack. The BT employee from Newcastle-upon-Tyne ended up sitting a few rows in front of him. She was knocked unconscious by the blast, but escaped with perforated ear drums, broken teeth, cuts and bruises. She broke down at the inquest as she described how a police officer stopped her going to help fellow passengers.</p>        </div>
    </li>
    </ul>
</div>

<script>
(function () {
    require(['special/2015/newsspec_11531/tavistock/ns_clickableguide_all-tavistock.js'], function () {
        require(['js/clickableguide/main-4', 'cssp!http://news.bbcimg.co.uk/news/special/2015/newsspec_11531/tavistock/ns_panels_core_domestic-tavistock_v8.css?csspHack'], function (ClickableGuide) {
            var myClickableGuide = new ClickableGuide('#ns_clickableguide-29176876', {
                next:          "Next",
                pagingDivider: "of",
                prev:          "Previous",
                nextImage:     "Next image",
                prevImage:     "Previous image"
            }, {
                nextPrevButtons:      false,
                responsive:           (window.bbcNewsResponsive || false),
                interactiveMinWidth:  976 + 47,
                interactiveMinHeight: 550,
                mask:                 '',
                panelsPosition:       'centre_of_interactive',
                zoomable_images:      false            });
        });
    });
}());
</script>

<div id="csspHack"></div>