<!--newsspec_11531 -->
<div id="newsspec-11531-responsive-image-include-1" class="ns-responsive-image-placeholder"></div>
<script type="text/javascript">
require(['jquery-1', 'http://news.bbcimg.co.uk/news/special/2015/newsspec_11297/art_direction_rwdimg/v5/js/artdirectionrwdimg.js'], function (ns_jquery, artDirectionRwdImg){
    artDirectionRwdImg(
        {
            "namespaceId": "newsspec-11531-responsive-image-include-1",
            "images": {
                    "305" : "2015/newsspec_11531/aldgate/img/7_7_aldgate_305.png",
                    "448" : "2015/newsspec_11531/aldgate/img/7_7_aldgate_448.png",
                    "624" : "2015/newsspec_11531/aldgate/img/7_7_aldgate_624.png"
                },
            "alt": "Location of bomber and passengers in the Aldgate blast",
            "caption": ""
        }
    );
});
</script>