<!--[if lt IE 9]>
<script src="http://static.bbci.co.uk/indepthtoolkit/6.0.0/js/vendor/polyfil.js"></script>
<![endif]-->
<style>
.ns-panel__clickable {
  display: none;
}
.ns-panel__hotspots {
  display: none;
}
.ns-panel__section-close{
  display: none;
}
.ns-panel--interactive .ns-panel__clickable {
  display: block;
}
.ns-panel--interactive .ns-panel__hotspots {
  display: block;
}
.ns-panel--interactive .ns-panel__video__cta{
  display: none;
}
body ul .ns-panel__section {
  background: none;
  list-style: none;
  margin: 0 0 1em;
  padding-left: 0;
}
</style>
<script>
document.body.className += " dyn_full";
</script>

<div class="idt__news ns-panel ns-wide-include" id="ns_clickableguide-10745641">

    <div class="ns-panel__clickable">INTERACTIVE</div>

    <div class="ns-panel__hotspots ns-panel__hotspots--thumbnail" style="height: 550px;">

                <noscript>
            <img src="http://c.files.bbci.co.uk/15C4D/production/_83956198_7_7_aldgate_976.png" width="976" height="550" alt="Location of those killed and those who survived the Aldgate bomb" class="no-replace"  />
        </noscript>

        <div class="idt-delayed-image-load ns-panel__context-image" data-src="http://c.files.bbci.co.uk/15C4D/production/_83956198_7_7_aldgate_976.png" data-alt="Location of those killed and those who survived the Aldgate bomb" ></div>

            
        
        <a href="#ns-panel__section-2" class="ns-panel__hotspot ns-panel__hotspot--2 ns-panel__hotspot--no-hover-border" style="position: absolute; left: 0px; top: 106px; width: 101px; height: 124px; ">
                            <div class="ns-panel__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel__caption-overlay ">
                    <p>Martine Wiltshire</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel__section-3" class="ns-panel__hotspot ns-panel__hotspot--3 ns-panel__hotspot--no-hover-border" style="position: absolute; left: 122px; top: 108px; width: 102px; height: 122px; ">
                            <div class="ns-panel__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel__caption-overlay ">
                    <p>Andrew Brown</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel__section-4" class="ns-panel__hotspot ns-panel__hotspot--4 ns-panel__hotspot--no-hover-border" style="position: absolute; left: 242px; top: 107px; width: 102px; height: 125px; ">
                            <div class="ns-panel__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel__caption-overlay ">
                    <p>Philip Duckworth</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel__section-5" class="ns-panel__hotspot ns-panel__hotspot--5 ns-panel__hotspot--no-hover-border" style="position: absolute; left: 363px; top: 106px; width: 101px; height: 109px; ">
                            <div class="ns-panel__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel__caption-overlay ">
                    <p>Bruce Lait</p>
                </span>
                    </a>

        
    
    </div>

    <ul class="ns-panel__sections">
                <li class="ns-panel__section ns-panel__section--int" id="ns-panel__section-2">

        <h2 class="ns-panel__section-header">Martine Wiltshire</h2>
        
        <a class="ns-panel__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel__section-img no-replace" src="http://c.files.bbci.co.uk/5203/production/_83959902_martine_wiltshire_gettycred.jpg" alt="Martine Wiltshire" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel__section-img" data-src="http://c.files.bbci.co.uk/5203/production/_83959902_martine_wiltshire_gettycred.jpg" data-alt="Martine Wiltshire"></div>
         
        <div class="ns-panel__section-text">
            <p>Martine Wiltshire, nee Wright, who competed in the London 2012 Paralympics, was just feet away from the bomber when the device went off. She lost both legs in the blast. 'I recall a white light in front of my eyes and a feeling of being thrown from side to side,' she said. Ms Wiltshire wept as she told the inquest how she owed her life to off-duty police officer Elizabeth Kenworthy, who gave her a belt to apply as a tourniquet to stem the bleeding. </p>        </div>
    </li>
    <li class="ns-panel__section ns-panel__section--int" id="ns-panel__section-3">

        <h2 class="ns-panel__section-header">Andrew Brown</h2>
        
        <a class="ns-panel__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel__section-sub-header"></h3>
        
        <div class="ns-panel__section-text">
            <p>Airport worker Andrew Brown, who lost a leg in the bombing, blacked out for 15 minutes after the blast. When he came round he first thought he had been electrocuted, but only realised how badly wounded he was when he tried to stand up to assist others in the train. 'As soon as I was conscious, I became aware of people moaning and calling for help,' he said. </p>        </div>
    </li>
    <li class="ns-panel__section ns-panel__section--int" id="ns-panel__section-4">

        <h2 class="ns-panel__section-header">Philip Duckworth</h2>
        
        <a class="ns-panel__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel__section-img no-replace" src="http://c.files.bbci.co.uk/C733/production/_83959905_philip_duckworth_bbccredit.jpg" alt="Philip Duckworth" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel__section-img" data-src="http://c.files.bbci.co.uk/C733/production/_83959905_philip_duckworth_bbccredit.jpg" data-alt="Philip Duckworth"></div>
         
        <div class="ns-panel__section-text">
            <p>The investment banker was so close to Shehzad Tanweer that he was blinded in one eye by a fragment of the bomber's shin-bone. Mr Duckworth described how he was thrown onto the tracks by the force of the blast and drifted in and out of consciousness. Coroner Lady Justice Hallett said his was 'an astonishing story' and that he had reduced the court to silence.</p>        </div>
    </li>
    <li class="ns-panel__section ns-panel__section--int" id="ns-panel__section-5">

        <h2 class="ns-panel__section-header">Bruce Lait</h2>
        
        <a class="ns-panel__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel__section-img no-replace" src="http://c.files.bbci.co.uk/F997/production/_83959836_bruce_lait_pacredit.jpg" alt="Bruce Lait" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel__section-img" data-src="http://c.files.bbci.co.uk/F997/production/_83959836_bruce_lait_pacredit.jpg" data-alt="Bruce Lait"></div>
         
        <div class="ns-panel__section-text">
            <p>The professional dancer from Ipswich was sitting reading a newspaper next to his dance partner further along the carriage from the bomber. Mr Lait suffered minor burns, cuts and burst eardrums and remains partially deaf. He told the inquest how he held the hand of victim Fiona Stevenson until she died. 'I tried to comfort her,' he said.</p>        </div>
    </li>
    </ul>
</div>

<script>
(function () {
    require(['special/2015/newsspec_11531/aldgate/ns_clickableguide_all-aldgate.js'], function () {
        require(['js/clickableguide/main', 'cssp!http://news.bbcimg.co.uk/news/special/2015/newsspec_11531/aldgate/ns_panels_core_domestic_aldgate_v8.css?csspHack'], function (ClickableGuide) {
            var myClickableGuide = new ClickableGuide('#ns_clickableguide-10745641', {
                next:          "Next",
                pagingDivider: "of",
                prev:          "Previous",
                nextImage:     "Next image",
                prevImage:     "Previous image"
            }, {
                nextPrevButtons:      false,
                responsive:           (window.bbcNewsResponsive || false),
                interactiveMinWidth:  976 + 47,
                interactiveMinHeight: 550,
                mask:                 '',
                panelsPosition:       'centre_of_interactive',
                zoomable_images:      false            });
        });
    });
}());
</script>

<div id="csspHack"></div>

    
