<!--[if lt IE 9]>
<script src="https://static.bbc.co.uk/indepthtoolkit/6.0.0/js/vendor/polyfil.js"></script>
<![endif]-->
<style>
.ns-panel-russell_sq__clickable {
  display: none;
}
.ns-panel-russell_sq__hotspots {
  display: none;
}
.ns-panel-russell_sq__section-close{
  display: none;
}
.ns-panel-russell_sq--interactive .ns-panel-russell_sq__clickable {
  display: block;
}
.ns-panel-russell_sq--interactive .ns-panel-russell_sq__hotspots {
  display: block;
}
.ns-panel-russell_sq--interactive .ns-panel-russell_sq__video__cta{
  display: none;
}
body ul .ns-panel-russell_sq__section {
  background: none;
  list-style: none;
  margin: 0 0 1em;
  padding-left: 0;
}
</style>
<script>
document.body.className += " dyn_full";
</script>

<div class="idt__news ns-panel-russell_sq ns-wide-include" id="ns_clickableguide-89230260">

    <div class="ns-panel-russell_sq__clickable">INTERACTIVE</div>

    <div class="ns-panel-russell_sq__hotspots ns-panel-russell_sq__hotspots--thumbnail" style="height: 554px;">

                <noscript>
            <img src="http://c.files.bbci.co.uk/6E23/production/_83959182_7_7_russell_square_976.png" width="976" height="554" alt="Location of those killed and those who survived the Russell Square blast" class="no-replace"  />
        </noscript>

        <div class="idt-delayed-image-load ns-panel-russell_sq__context-image" data-src="http://c.files.bbci.co.uk/6E23/production/_83959182_7_7_russell_square_976.png" data-alt="Location of those killed and those who survived the Russell Square blast" ></div>

            
        
        <a href="#ns-panel-russell_sq__section-2" class="ns-panel-russell_sq__hotspot ns-panel-russell_sq__hotspot--2 ns-panel-russell_sq__hotspot--no-hover-border" style="position: absolute; left: 0px; top: 113px; width: 101px; height: 123px; ">
                            <div class="ns-panel-russell_sq__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-russell_sq__caption-overlay ">
                    <p>Paul Mitchell</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-russell_sq__section-3" class="ns-panel-russell_sq__hotspot ns-panel-russell_sq__hotspot--3 ns-panel-russell_sq__hotspot--no-hover-border" style="position: absolute; left: 123px; top: 114px; width: 101px; height: 108px; ">
                            <div class="ns-panel-russell_sq__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-russell_sq__caption-overlay ">
                    <p>Lilian Ajayi</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-russell_sq__section-4" class="ns-panel-russell_sq__hotspot ns-panel-russell_sq__hotspot--4 ns-panel-russell_sq__hotspot--no-hover-border" style="position: absolute; left: 240px; top: 113px; width: 106px; height: 125px; ">
                            <div class="ns-panel-russell_sq__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-russell_sq__caption-overlay ">
                    <p>Paul Glennerster</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-russell_sq__section-5" class="ns-panel-russell_sq__hotspot ns-panel-russell_sq__hotspot--5 ns-panel-russell_sq__hotspot--no-hover-border" style="position: absolute; left: 362px; top: 113px; width: 103px; height: 107px; ">
                            <div class="ns-panel-russell_sq__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-russell_sq__caption-overlay ">
                    <p>Gill Hicks</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-russell_sq__section-6" class="ns-panel-russell_sq__hotspot ns-panel-russell_sq__hotspot--6 ns-panel-russell_sq__hotspot--no-hover-border" style="position: absolute; left: 482px; top: 113px; width: 102px; height: 123px; ">
                            <div class="ns-panel-russell_sq__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-russell_sq__caption-overlay ">
                    <p>Alison McCarthy</p>
                </span>
                    </a>

        
    
        
        <a href="#ns-panel-russell_sq__section-7" class="ns-panel-russell_sq__hotspot ns-panel-russell_sq__hotspot--7 ns-panel-russell_sq__hotspot--no-hover-border" style="position: absolute; left: 603px; top: 114px; width: 102px; height: 121px; ">
                            <div class="ns-panel-russell_sq__hotspot--legacy-ie-rollover-fix"></div>
                                <span class="ns-panel-russell_sq__caption-overlay ">
                    <p>Philip Patsalos</p>
                </span>
                    </a>

        
    
    </div>

    <ul class="ns-panel-russell_sq__sections">
                <li class="ns-panel-russell_sq__section ns-panel-russell_sq__section--int" id="ns-panel-russell_sq__section-2">

        <h2 class="ns-panel-russell_sq__section-header">Paul Mitchell</h2>
        
        <a class="ns-panel-russell_sq__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-russell_sq__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-russell_sq__section-img no-replace" src="http://c.files.bbci.co.uk/D863/production/_83959355_paul_mitchell_credit_624.jpg" alt="Paul Mitchell" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-russell_sq__section-img" data-src="http://c.files.bbci.co.uk/D863/production/_83959355_paul_mitchell_credit_624.jpg" data-alt="Paul Mitchell"></div>
         
        <div class="ns-panel-russell_sq__section-text">
            <p>Mr Mitchell, who was on his way to work on Regent Street, told the inquest the carriage had been crammed when 'an extremely loud pop and a very bright yellow light' went off. He was thrown to the ground by the force of the blast and recalls 'complete and utter pandemonium'. Mr Mitchell attributes his survival to fellow passenger Julie Gruen, who helped him tie a tourniquet around his damaged leg using her coat and a sanitary towel.</p>        </div>
    </li>
    <li class="ns-panel-russell_sq__section ns-panel-russell_sq__section--int" id="ns-panel-russell_sq__section-3">

        <h2 class="ns-panel-russell_sq__section-header">Lilian Ajayi</h2>
        
        <a class="ns-panel-russell_sq__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-russell_sq__section-sub-header"></h3>
        
        <div class="ns-panel-russell_sq__section-text">
            <p>Ms Ajayi was going to sit down on a seat but gave it up for another female passenger. That passenger later died. She described hearing a 'boom' and then seeing scenes of the injured piled up 'like a laundry basket'. She recalled trying to help a man, but realised his leg injury was too severe to move him. She also did not want to tell him about the extent of his injuries, she said.</p>        </div>
    </li>
    <li class="ns-panel-russell_sq__section ns-panel-russell_sq__section--int" id="ns-panel-russell_sq__section-4">

        <h2 class="ns-panel-russell_sq__section-header">Paul Glennerster</h2>
        
        <a class="ns-panel-russell_sq__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-russell_sq__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-russell_sq__section-img no-replace" src="http://c.files.bbci.co.uk/4AFB/production/_83959191_paul_glennerster_creditrex_.jpg" alt="Paul Glennerster" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-russell_sq__section-img" data-src="http://c.files.bbci.co.uk/4AFB/production/_83959191_paul_glennerster_creditrex_.jpg" data-alt="Paul Glennerster"></div>
         
        <div class="ns-panel-russell_sq__section-text">
            <p>Paul Glennerster told the inquest how he 'picked up' his badly damaged limb and 'hopped' off the bombed train. The keen footballer managed to get himself on to the tracks before being stretchered to the surface. He was helped by train driver Thomas Nairn, who used his belt to apply a tourniquet to Mr Glennerster's leg. Mr Glennerster was praised by the coroner for his 'amazing presence of mind'.</p>        </div>
    </li>
    <li class="ns-panel-russell_sq__section ns-panel-russell_sq__section--int" id="ns-panel-russell_sq__section-5">

        <h2 class="ns-panel-russell_sq__section-header">Gill Hicks</h2>
        
        <a class="ns-panel-russell_sq__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-russell_sq__section-sub-header"></h3>

                        <noscript>
        <img class="ns-panel-russell_sq__section-img no-replace" src="http://c.files.bbci.co.uk/B153/production/_83959354_gill_hicks__624_creditepa.jpg" alt="Gill Hicks" width="624" height="351"  />
    </noscript>
    <div class="idt-delayed-image-load ns-panel-russell_sq__section-img" data-src="http://c.files.bbci.co.uk/B153/production/_83959354_gill_hicks__624_creditepa.jpg" data-alt="Gill Hicks"></div>
         
        <div class="ns-panel-russell_sq__section-text">
            <p>Ms Hicks lost both legs in the blast but saved her own life by tying tourniquets to her severed limbs. She told the inquest she thought she was having a heart attack when the bomb exploded. She passed out and awoke on a seat to discover her injuries. She ripped her scarf in half and tied it around each leg before lifting what remained of them over the armrest of a seat. She was praised by the coroner for her 'indomitable spirit'.</p>        </div>
    </li>
    <li class="ns-panel-russell_sq__section ns-panel-russell_sq__section--int" id="ns-panel-russell_sq__section-6">

        <h2 class="ns-panel-russell_sq__section-header">Alison McCarthy</h2>
        
        <a class="ns-panel-russell_sq__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-russell_sq__section-sub-header"></h3>
        
        <div class="ns-panel-russell_sq__section-text">
            <p>Alison McCarthy, who joined the train at Finsbury Park, described how she passed out when the bomb went off. She woke up under injured people and bodies and her feet were embedded with glass. But she went on to help fellow passengers by applying tourniquets and keeping them conscious through conversation. 'It didn't occur to me to leave,' she said.</p>        </div>
    </li>
    <li class="ns-panel-russell_sq__section ns-panel-russell_sq__section--int" id="ns-panel-russell_sq__section-7">

        <h2 class="ns-panel-russell_sq__section-header">Philip Patsalos</h2>
        
        <a class="ns-panel-russell_sq__section-close" href="#">&times;</a>
        
        <h3 class="ns-panel-russell_sq__section-sub-header"></h3>
        
        <div class="ns-panel-russell_sq__section-text">
            <p>Prof Patsalos, who lost a leg in the blast, told the inquest he survived because he was sitting in his 'favourite' seat. He told the coroner he would have been killed if he had been sitting in his second favourite seat, which was inches from where the bomb detonated. The epilepsy specialist at University College London's Institute of Neurology said: 'How I survived, I don't know. Somebody saved me... I'm grateful.'</p>        </div>
    </li>
    </ul>
</div>

<script>
(function () {
    require(['special/2015/newsspec_11531/russell_sq/ns_clickableguide_all-russell_sq.js'], function () {
        require(['js/clickableguide/main-3', 'cssp!http://news.bbcimg.co.uk/news/special/2015/newsspec_11531/russell_sq/ns_panels_core_domestic-russell_sq_v9.css?csspHack'], function (ClickableGuide) {
            var myClickableGuide = new ClickableGuide('#ns_clickableguide-89230260', {
                next:          "Next",
                pagingDivider: "of",
                prev:          "Previous",
                nextImage:     "Next image",
                prevImage:     "Previous image"
            }, {
                nextPrevButtons:      false,
                responsive:           (window.bbcNewsResponsive || false),
                interactiveMinWidth:  976 + 47,
                interactiveMinHeight: 554,
                mask:                 '',
                panelsPosition:       'centre_of_interactive',
                zoomable_images:      false            });
        });
    });
}());
</script>

<div id="csspHack"></div>